### ISSUE TITLE
Fatal error on installation

### ISSUE THREAD

**Issue by Al-Rozhkov** [backdrop-contrib/easy_xmlsitemap#1]
At first thank you for your job. You are doing very much needed for Backdrop SEO oriented modules.

Unfortunately I can't install this module (version = 1.0.1).

Fatal error: Can't use function return value in write context in /var/www/vhosts/.../modules/easy_xmlsitemap/easy_xmlsitemap.module on line 272

**Comment by findlabnet** [comment]
@Al-Rozhkov thank you for find out this bug. 
Fixed in version 1.0.2

**Comment by Al-Rozhkov** [comment]
Thanks a lot!
