### ISSUE TITLE
last_build_date should be stored in state, not config

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/easy_xmlsitemap#2]
Hi Vlad, thanks for creating this module. Nice and easy.

The last_build_date variable should be stored in state with state_set/get as per https://api.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/state_get/1. It is just like the example given for last time cron was run.

This variable is environment specific and shouldn't be transferred between environments.

Also, you may want to rename it to "easy_xmlsitemap_last_build_date" so that there's less chance of a clash with other state variables.

**Comment by findlabnet** [comment]
Thanks Herb, you absolutely right! Fixed in [v.1.0.5](https://github.com/backdrop-contrib/easy_xmlsitemap/releases/tag/1.x-1.0.5).
