### ISSUE TITLE
Join With Drupal XML Sitemap Port?

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-contrib/easy_xmlsitemap#3]
Hello @findlabnet!

There is current work going on to port the Drupal XML sitemap module to Backdrop:
- [https://github.com/alexfinnarn/backdrop-xml-sitemap](https://github.com/alexfinnarn/backdrop-xml-sitemap)
- alexfinnarn/backdrop-xml-sitemap#7

What are your thoughts on joining forces in maintaining the Drupal port of the module? Do you think this module has different goals? or do you think both modules can be combined?

Cheers, 
Alex

**Comment by findlabnet** [comment]
First of all - thank you for invitation, @alexfinnarn!
And now in order of questions.
1) At this time I have not plan to work for this port of Drupal module.

2) You right, my module have very different goals, specifically not intended for upgrade from old Drupal sites, for newly created Backdrop only, moreover it is first and one implementation of this functionality for Backdrop.

For now, for Backdrop not implemented yet important modules such as i18n, so in any case we can have partial compatibility only in ported code. 

My motivation: I personally do not want to have extra elements which ignored by search engines such as human-readable sitemap page (pulling  additional JS, CSS and XSL transformations) or optional URLs attributes "priority" and "lastmod".
I think each one must have option for select type of complexity to use.

3) So, as described above, modules can not be combined.

Maybe I should add this information to module documentation. 

Regards,
Vladimir.
